[package]
name = "dedede"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
softbuffer = "0.3.1"
stl_io = "0.7.0"
tobj = "4.0.0"
ultraviolet = "0.9.2"
winit = "0.28.6"
